# Site settings
title: "Bad Bad Kitty Kat"
description: "The new blog."
baseurl: ""
url: "http://badbadkitty.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "about"
    url: /about
  - title: "rss"
    url: /feed.xml
